# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('u_id', models.CharField(max_length=50, unique=True)),
                ('u_name', models.CharField(blank=True, max_length=100, null=True)),
                ('u_weibo_count', models.IntegerField(blank=True, null=True)),
                ('u_following', models.IntegerField(blank=True, null=True)),
                ('u_fans', models.IntegerField(blank=True, null=True)),
                ('u_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('u_region', models.CharField(blank=True, max_length=50, null=True)),
                ('u_birthday', models.CharField(blank=True, max_length=20, null=True)),
                ('u_introduction', models.TextField(blank=True, null=True)),
                ('u_tags', models.CharField(blank=True, max_length=100, null=True)),
                ('u_school', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeiboInfo',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('u_id', models.CharField(max_length=50)),
                ('w_content', models.TextField(blank=True, null=True)),
                ('w_type', models.CharField(blank=True, max_length=20, null=True)),
                ('w_day', models.DateField(blank=True, null=True)),
                ('w_time', models.TimeField(blank=True, null=True)),
                ('w_client', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'weibo_info',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='systemuser',
            options={'managed': False},
        ),
    ]
