# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderOptions',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=255)),
                ('delay', models.IntegerField(blank=True)),
                ('cookies_T_WM', models.CharField(max_length=255)),
                ('cookies_SUHB', models.CharField(max_length=255)),
                ('cookies_SUB', models.CharField(max_length=255)),
                ('cookies_gsid_CTandWM', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('pages', models.IntegerField(blank=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spider_options',
                'managed': False,
            },
        ),
    ]
